@startuml
actor "Representante R+S" as representante
boundary "GUI" as gui <<fronteira>>



control "AprovacaoController" as aprovacaoController<<controller>>

collections "Candidatos" as candidatos
collections "Voluntarios" as voluntarios


collections "Recomendacoes" as recomendacoes
entity "Candidato" as candidato
entity "Voluntario" as voluntario

representante -> gui: aprovaVoluntario(idVoluntario, recomendacao)
activate gui
    gui -> aprovacaoController: aprovaVoluntario(idVoluntario, recomendacao)
    activate aprovacaoController
        aprovacaoController -> recomendacoes: salvaRecomendacao(recomendacao)
        activate recomendacoes
            recomendacoes --> aprovacaoController: recomendacao
        deactivate recomendacoes
        aprovacaoController -> voluntarios: procuraVoluntario(idVoluntario)
        activate voluntarios
            voluntarios -> voluntario: get(idVoluntario)
            activate voluntario
                voluntario --> voluntarios: voluntario
            
            voluntarios --> aprovacaoController: voluntario
        
        aprovacaoController -> voluntario: geraLoginSenhaVoluntario(voluntario)
        deactivate voluntario
        aprovacaoController -> voluntarios: salvaVoluntario(voluntario)
        
        deactivate voluntarios

        aprovacaoController -> aprovacaoController: enviaEmailLoginInstrucao(voluntarioEmail, voluntarioLogin, voluntarioSenha)
        aprovacaoController -> aprovacaoController: enviaEmailResultadoAfiliacaoRecomendacao(voluntarioEmail, recomendacao)

        aprovacaoController --> gui: "sucesso"
    deactivate aprovacaoController
deactivate gui
    

@enduml
``````plantuml
@startuml
actor "Representante R+S" as representante
boundary "GUI" as gui <<fronteira>>



control "AprovacaoController" as aprovacaoController<<controller>>

collections "Candidatos" as candidatos
collections "Voluntarios" as voluntarios


collections "Recomendacoes" as recomendacoes
entity "Candidato" as candidato
entity "Voluntario" as voluntario

representante -> gui: aprovaVoluntario(idVoluntario, recomendacao)
activate gui
    gui -> aprovacaoController: aprovaVoluntario(idVoluntario, recomendacao)
    activate aprovacaoController
        aprovacaoController -> recomendacoes: salvaRecomendacao(recomendacao)
        activate recomendacoes
            recomendacoes --> aprovacaoController: recomendacao
        deactivate recomendacoes
        aprovacaoController -> voluntarios: procuraVoluntario(idVoluntario)
        activate voluntarios
            voluntarios -> voluntario: get(idVoluntario)
            activate voluntario
                voluntario --> voluntarios: voluntario
            
            voluntarios --> aprovacaoController: voluntario
        
        aprovacaoController -> voluntario: geraLoginSenhaVoluntario(voluntario)
        deactivate voluntario
        aprovacaoController -> voluntarios: salvaVoluntario(voluntario)
        
        deactivate voluntarios

        aprovacaoController -> aprovacaoController: enviaEmailLoginInstrucao(voluntarioEmail, voluntarioLogin, voluntarioSenha)
        aprovacaoController -> aprovacaoController: enviaEmailResultadoAfiliacaoRecomendacao(voluntarioEmail, recomendacao)

        aprovacaoController --> gui: "sucesso"
    deactivate aprovacaoController
deactivate gui
    

@enduml
