@startuml

actor "Representante R+S" as representante
boundary "GUI" as gui <<fronteira>>
control "AfiliacaoController" as afiliacaoController <<controller>>
control "CandidatoController" as candidatoController <<controller>>

collections "PedidoAfiliacao" as pedidoAfiliacao
collections "Candidatos" as candidatos
collections "Voluntarios" as voluntarios



entity "Candidato" as candidato
entity "Perfil" as perfil

collections "Habilidades" as habilidades
entity "Habilidade" as habilidade

collections "Interesses" as interesses
entity "Interesse" as interesse


representante -> gui: buscaCandidatosPendentes()
activate gui

    gui -> afiliacaoController: buscaCandidatosPendentes()
    activate afiliacaoController

        afiliacaoController -> pedidoAfiliacao: buscaCandidatosPendentes()
        activate pedidoAfiliacao
            
            pedidoAfiliacao --> candidatos: buscaCandidatos("pendente")
            activate candidatos
                candidatos --> candidato: getCandidato("pendente")
                activate candidato
                    candidato ---> candidatos: candidatoPendente
                deactivate candidato
                candidatos ---> pedidoAfiliacao: listaCandidatosPendentes
            deactivate candidatos
            pedidoAfiliacao --> afiliacaoController: listaCandidatosPendentes
            

        deactivate pedidoAfiliacao

        afiliacaoController --> gui: listaCandidatosPendentes
    deactivate afiliacaoController

deactivate gui 


representante -> gui: exibeInformacaoDetalhadaCandidato(id)
activate gui

    gui -> candidatoController: exibeInformacaoDetalhadaCandidato(id)
    activate candidatoController

        candidatoController -> candidatos: buscaCandidato(id)
        activate candidatos

            candidatos -> candidato: get(id)
            activate candidato

                candidato --> candidatos: Candidato

            deactivate candidato
            candidatos --> candidatoController: Candidato

        deactivate candidatos
        candidatoController -> candidato: getPerfilCandidato()
        activate candidato
            perfil --> candidato: perfil
            activate perfil
        candidato --> candidatoController: perfil
        candidatoController -> candidato: getHabilidadesCandidato() 
            candidato -> perfil: getHabilidades()

                perfil -> habilidades: getHabilidades()
                activate habilidades
                    habilidades -> habilidade: getHabilidade()
                    activate habilidade
                        habilidade --> habilidades: habilidade
                    deactivate habilidade
                    habilidades -> perfil: habilidadesPerfil
                deactivate habilidades
                perfil --> candidato: habilidadesPerfil
            candidato --> candidatoController: habilidadesCandidato
        candidatoController -> candidato: getInteressesCandidato()
            candidato -> perfil: getInteresses()
            perfil -> interesses: getInteresses()
                activate interesses
                    interesses -> interesse: getInteresse()
                    activate interesse
                        interesse --> interesses: interesse
                    deactivate interesse
                    interesses -> perfil: interessesPerfil
                deactivate interesses
            perfil --> candidato: interessesPerfil
            deactivate perfil
            candidato --> candidatoController: interesseCandidato
        candidatoController --> gui: informacoesDetalhadas

    deactivate candidatoController

deactivate gui



@enduml