@startuml
actor "Representante R+S" as representante
boundary "GUI" as gui <<fronteira>>
control "CandidatoController" as candidatoController <<controller>>
control "ONGController" as ongController<<controller>>

collections "Candidatos" as candidatos
collections "ONGs" as ongs
collections "Campanhas" as campanhas
collections "Perfis" as perfis

entity "Perfil" as perfil
entity "ONG" as ong
entity "Candidato" as candidato
entity "Recomendacao" as recomendacao
entity "Campanha" as campanha

representante -> gui: solicitaAprovacaoCandidato(id)
activate gui
    gui -> candidatoController: solicitaAprovacaoCandidato(id)
    activate candidatoController
        candidatoController -> candidatos: buscaCandidato(id)
        activate candidatos
            
            candidatos -> candidato: get(id)
            activate candidato
                candidato --> candidatos: candidato
            deactivate candidato

        candidatos --> candidatoController: candidato
        deactivate candidatos

        candidatoController -> candidato: mudaSituacao(candidato)
        activate candidato
            candidato --> candidatoController: candidato
        deactivate candidato

        candidatoController -> candidatos: salva(candidato)

        activate candidatos
            candidatos--> candidatoController: candidato
        deactivate candidatos

    candidatoController --> gui: candidato
    deactivate candidatoController
deactivate gui

@enduml