@startuml

actor "Representante R+S" as representante
boundary "GUI" as gui <<fronteira>>
control "AfiliacaoController" as afiliacaoController <<controller>>
control "CandidatoController" as candidatoController <<controller>>

collections "PedidoAfiliacao" as pedidoAfiliacao
collections "Candidatos" as candidatos
collections "Voluntarios" as voluntarios

entity "Candidato" as candidato


representante -> gui: buscaCandidatosPendentes()
activate gui

    gui -> afiliacaoController: buscaCandidatosPendentes()
    activate afiliacaoController

        afiliacaoController -> pedidoAfiliacao: buscaCandidatosPendentes()
        activate pedidoAfiliacao
            group enquanto houver candidatos pendentes
                pedidoAfiliacao -> candidato: getCandidato()
                activate candidato
                    
                    candidato --> pedidoAfiliacao: Candidato

                deactivate candidato
            end
            pedidoAfiliacao --> afiliacaoController: Candidatos

            deactivate pedidoAfiliacao

        afiliacaoController --> gui: Candidatos
        deactivate afiliacaoController

deactivate gui 


representante -> gui: exibeInformacaoDetalhadaCandidato(id)
activate gui

    gui -> candidatoController: exibeInformacaoDetalhadaCandidato(id)
    activate candidatoController

        candidatoController -> candidatos: buscaCandidato(id)
        activate candidatos

            candidatos -> candidato: get(id)
            activate candidato

                candidato --> candidatos: Candidato

            deactivate candidato
            candidatos --> candidatoController: Candidato

        deactivate candidatos
        candidatoController --> gui: Candidato

    deactivate candidatoController

deactivate gui



@enduml
