@startuml
actor "Representante R+S" as representante
boundary "GUI" as gui <<fronteira>>
control "CandidatoController" as candidatoController <<controller>>
control "ONGController" as ongController<<controller>>

collections "Candidatos" as candidatos
collections "ONGs" as ongs
collections "Campanhas" as campanhas
collections "Perfis" as perfis
collections "Vagas" as vagas

entity "Perfil" as perfil
entity "ONG" as ong
entity "Candidato" as candidato
entity "Recomendacao" as recomendacao
entity "Campanha" as campanha
entity "Vaga" as vaga


representante -> gui: solicitaçãoRecomendacaoOngParceira(perfil)
activate gui
    gui -> ongController: solicitaçãoRecomendacaoOngParceira(perfil)
    activate ongController
        ongController -> vagas: retornaVagasDeAcordoComPerfil(perfil)
        activate vagas
            vagas --> ongController: listaVagas
            loop 'Para cada vaga em listaVagas'
                ongController -> vaga: retornaCampanha()
                activate vaga
                    vaga -> campanha: getOng()
                    activate campanha
                        campanha --> vaga: ong
                    deactivate campanha
                    vaga --> ongController: ong
                deactivate vaga
            end
            
            activate campanha

            


        ongController -> recomendacao: create
        activate recomendacao
                recomendacao --> ongController: recomendacao
                ongController -> recomendacao: associaOngs(ongs)
                ongController -> recomendacao: associaCampanha(ongs)
                recomendacao -> ong: getCampanhas()
                activate ong
                ong -> campanhas: getCampanha()
                activate campanhas
                campanhas -> campanha: get()
                activate campanha
                    campanha --> campanhas: campanha
                deactivate campanha
                campanhas --> ong: camapanhas
                deactivate campanhas
                ong --> recomendacao: campanhas
                deactivate ong
            
        deactivate recomendacao
        ongController --> gui: recomendação 
    deactivate ongController
deactivate gui


@enduml